#!/bin/bash

sed -i 's/AI1.MEZ1_AI_CH1_M/$(dev)$(ssa)-01:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH1_C/$(dev)$(ssa)-01:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH1_M/$(dev)$(ssa)-01:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH1_C/$(dev)$(ssa)-01:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH4_M/$(dev)$(ssa)-02:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH4_C/$(dev)$(ssa)-02:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH4_M/$(dev)$(ssa)-02:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH4_C/$(dev)$(ssa)-02:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH1_M/$(dev)$(ssa)-03:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH1_C/$(dev)$(ssa)-03:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH1_M/$(dev)$(ssa)-03:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH1_C/$(dev)$(ssa)-03:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH4_M/$(dev)$(ssa)-04:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH4_C/$(dev)$(ssa)-04:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH4_M/$(dev)$(ssa)-04:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH4_C/$(dev)$(ssa)-04:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH1_M/$(dev)$(ssa)-05:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH1_C/$(dev)$(ssa)-05:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH1_M/$(dev)$(ssa)-05:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH1_C/$(dev)$(ssa)-05:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH4_M/$(dev)$(ssa)-06:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH4_C/$(dev)$(ssa)-06:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH4_M/$(dev)$(ssa)-06:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH4_C/$(dev)$(ssa)-06:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH1_M/$(dev)$(ssa)-07:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH1_C/$(dev)$(ssa)-07:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH1_M/$(dev)$(ssa)-07:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH1_C/$(dev)$(ssa)-07:IDDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH4_M/$(dev)$(ssa)-08:IDADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH4_C/$(dev)$(ssa)-08:IDADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH4_M/$(dev)$(ssa)-08:IDDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH4_C/$(dev)$(ssa)-08:IDDAC_B/g'    IPMScalibration.bob

sed -i 's/AI1.MEZ1_AI_CH2_M/$(dev)$(ssa)-01:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH2_C/$(dev)$(ssa)-01:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH2_M/$(dev)$(ssa)-01:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH2_C/$(dev)$(ssa)-01:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH5_M/$(dev)$(ssa)-02:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH5_C/$(dev)$(ssa)-02:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH5_M/$(dev)$(ssa)-02:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH5_C/$(dev)$(ssa)-02:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH2_M/$(dev)$(ssa)-03:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH2_C/$(dev)$(ssa)-03:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH2_M/$(dev)$(ssa)-03:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH2_C/$(dev)$(ssa)-03:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH5_M/$(dev)$(ssa)-04:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH5_C/$(dev)$(ssa)-04:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH5_M/$(dev)$(ssa)-04:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH5_C/$(dev)$(ssa)-04:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH2_M/$(dev)$(ssa)-05:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH2_C/$(dev)$(ssa)-05:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH2_M/$(dev)$(ssa)-05:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH2_C/$(dev)$(ssa)-05:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH5_M/$(dev)$(ssa)-06:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH5_C/$(dev)$(ssa)-06:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH5_M/$(dev)$(ssa)-06:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH5_C/$(dev)$(ssa)-06:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH2_M/$(dev)$(ssa)-07:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH2_C/$(dev)$(ssa)-07:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH2_M/$(dev)$(ssa)-07:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH2_C/$(dev)$(ssa)-07:VDSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH5_M/$(dev)$(ssa)-08:VDSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH5_C/$(dev)$(ssa)-08:VDSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH5_M/$(dev)$(ssa)-08:VDSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH5_C/$(dev)$(ssa)-08:VDSDAC_B/g'    IPMScalibration.bob

sed -i 's/AI1.MEZ1_AI_CH3_M/$(dev)$(ssa)-01:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH3_C/$(dev)$(ssa)-01:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH3_M/$(dev)$(ssa)-01:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH3_C/$(dev)$(ssa)-01:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH6_M/$(dev)$(ssa)-02:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH6_C/$(dev)$(ssa)-02:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH6_M/$(dev)$(ssa)-02:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH6_C/$(dev)$(ssa)-02:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH3_M/$(dev)$(ssa)-03:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH3_C/$(dev)$(ssa)-03:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH3_M/$(dev)$(ssa)-03:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH3_C/$(dev)$(ssa)-03:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH6_M/$(dev)$(ssa)-04:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_CH6_C/$(dev)$(ssa)-04:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH6_M/$(dev)$(ssa)-04:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI1.MEZ2_AI_DAC_CH6_C/$(dev)$(ssa)-04:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH3_M/$(dev)$(ssa)-05:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH3_C/$(dev)$(ssa)-05:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH3_M/$(dev)$(ssa)-05:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH3_C/$(dev)$(ssa)-05:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH6_M/$(dev)$(ssa)-06:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH6_C/$(dev)$(ssa)-06:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH6_M/$(dev)$(ssa)-06:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH6_C/$(dev)$(ssa)-06:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH3_M/$(dev)$(ssa)-07:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH3_C/$(dev)$(ssa)-07:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH3_M/$(dev)$(ssa)-07:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH3_C/$(dev)$(ssa)-07:VGSDAC_B/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH6_M/$(dev)$(ssa)-08:VGSADC_M/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_CH6_C/$(dev)$(ssa)-08:VGSADC_B/g'        IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH6_M/$(dev)$(ssa)-08:VGSDAC_M/g'    IPMScalibration.bob
sed -i 's/AI2.MEZ2_AI_DAC_CH6_C/$(dev)$(ssa)-08:VGSDAC_B/g'    IPMScalibration.bob

sed -i 's/RF1.MEZ1_AI_CH1_M/$(dev)$(ssa)-01:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_CH1_C/$(dev)$(ssa)-01:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH1_M/$(dev)$(ssa)-01:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH1_C/$(dev)$(ssa)-01:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_CH3_M/$(dev)$(ssa)-02:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_CH3_C/$(dev)$(ssa)-02:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH3_M/$(dev)$(ssa)-02:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH3_C/$(dev)$(ssa)-02:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH1_M/$(dev)$(ssa)-03:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH1_C/$(dev)$(ssa)-03:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH1_M/$(dev)$(ssa)-03:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH1_C/$(dev)$(ssa)-03:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH3_M/$(dev)$(ssa)-04:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH3_C/$(dev)$(ssa)-04:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH3_M/$(dev)$(ssa)-04:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH3_C/$(dev)$(ssa)-04:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH1_M/$(dev)$(ssa)-05:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH1_C/$(dev)$(ssa)-05:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH1_M/$(dev)$(ssa)-05:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH1_C/$(dev)$(ssa)-05:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH3_M/$(dev)$(ssa)-06:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH3_C/$(dev)$(ssa)-06:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH3_M/$(dev)$(ssa)-06:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH3_C/$(dev)$(ssa)-06:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH1_M/$(dev)$(ssa)-07:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH1_C/$(dev)$(ssa)-07:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH1_M/$(dev)$(ssa)-07:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH1_C/$(dev)$(ssa)-07:RFFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH3_M/$(dev)$(ssa)-08:RFFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH3_C/$(dev)$(ssa)-08:RFFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH3_M/$(dev)$(ssa)-08:RFFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH3_C/$(dev)$(ssa)-08:RFFwdDAC_B/g'    IPMScalibration.bob

sed -i 's/RF1.MEZ1_AI_CH2_M/$(dev)$(ssa)-01:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_CH2_C/$(dev)$(ssa)-01:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH2_M/$(dev)$(ssa)-01:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH2_C/$(dev)$(ssa)-01:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_CH4_M/$(dev)$(ssa)-02:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_CH4_C/$(dev)$(ssa)-02:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH4_M/$(dev)$(ssa)-02:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ1_AI_DAC_CH4_C/$(dev)$(ssa)-02:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH2_M/$(dev)$(ssa)-03:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH2_C/$(dev)$(ssa)-03:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH2_M/$(dev)$(ssa)-03:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH2_C/$(dev)$(ssa)-03:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH4_M/$(dev)$(ssa)-04:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_CH4_C/$(dev)$(ssa)-04:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH4_M/$(dev)$(ssa)-04:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF1.MEZ2_AI_DAC_CH4_C/$(dev)$(ssa)-04:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH2_M/$(dev)$(ssa)-05:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH2_C/$(dev)$(ssa)-05:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH2_M/$(dev)$(ssa)-05:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH2_C/$(dev)$(ssa)-05:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH4_M/$(dev)$(ssa)-06:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_CH4_C/$(dev)$(ssa)-06:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH4_M/$(dev)$(ssa)-06:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ1_AI_DAC_CH4_C/$(dev)$(ssa)-06:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH2_M/$(dev)$(ssa)-07:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH2_C/$(dev)$(ssa)-07:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH2_M/$(dev)$(ssa)-07:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH2_C/$(dev)$(ssa)-07:RFRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH4_M/$(dev)$(ssa)-08:RFRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_CH4_C/$(dev)$(ssa)-08:RFRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH4_M/$(dev)$(ssa)-08:RFRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF2.MEZ2_AI_DAC_CH4_C/$(dev)$(ssa)-08:RFRefDAC_B/g'    IPMScalibration.bob

sed -i 's/TEMP.MEZ1_AI_CH1_M/$(dev)$(ssa)-01:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH1_C/$(dev)$(ssa)-01:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH1_M/$(dev)$(ssa)-01:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH1_C/$(dev)$(ssa)-01:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH2_M/$(dev)$(ssa)-02:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH2_C/$(dev)$(ssa)-02:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH2_M/$(dev)$(ssa)-02:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH2_C/$(dev)$(ssa)-02:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH3_M/$(dev)$(ssa)-03:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH3_C/$(dev)$(ssa)-03:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH3_M/$(dev)$(ssa)-03:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH3_C/$(dev)$(ssa)-03:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH4_M/$(dev)$(ssa)-04:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH4_C/$(dev)$(ssa)-04:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH4_M/$(dev)$(ssa)-04:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH4_C/$(dev)$(ssa)-04:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH5_M/$(dev)$(ssa)-05:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH5_C/$(dev)$(ssa)-05:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH5_M/$(dev)$(ssa)-05:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH5_C/$(dev)$(ssa)-05:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH6_M/$(dev)$(ssa)-06:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH6_C/$(dev)$(ssa)-06:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH6_M/$(dev)$(ssa)-06:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH6_C/$(dev)$(ssa)-06:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH7_M/$(dev)$(ssa)-07:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH7_C/$(dev)$(ssa)-07:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH7_M/$(dev)$(ssa)-07:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH7_C/$(dev)$(ssa)-07:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH8_M/$(dev)$(ssa)-08:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH8_C/$(dev)$(ssa)-08:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH8_M/$(dev)$(ssa)-08:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH8_C/$(dev)$(ssa)-08:TEMPDAC_B/g'    IPMScalibration.bob

sed -i 's/TEMP.MEZ1_AI_CH9_M/$(dev)$(ssa)-09:TEMPADC_M/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH9_C/$(dev)$(ssa)-09:TEMPADC_B/g'        IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH9_M/$(dev)$(ssa)-09:TEMPDAC_M/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH9_C/$(dev)$(ssa)-09:TEMPDAC_B/g'    IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH10_M/$(dev)$(ssa)-10:TEMPADC_M/g'       IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH10_C/$(dev)$(ssa)-10:TEMPADC_B/g'       IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH10_M/$(dev)$(ssa)-10:TEMPDAC_M/g'   IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH10_C/$(dev)$(ssa)-10:TEMPDAC_B/g'   IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH11_M/$(dev)$(ssa)-11:TEMPADC_M/g'       IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH11_C/$(dev)$(ssa)-11:TEMPADC_B/g'       IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH11_M/$(dev)$(ssa)-11:TEMPDAC_M/g'   IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH11_C/$(dev)$(ssa)-11:TEMPDAC_B/g'   IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH12_M/$(dev)$(ssa)-12:TEMPADC_M/g'       IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_CH12_C/$(dev)$(ssa)-12:TEMPADC_B/g'       IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH12_M/$(dev)$(ssa)-12:TEMPDAC_M/g'   IPMScalibration.bob
sed -i 's/TEMP.MEZ1_AI_DAC_CH12_C/$(dev)$(ssa)-12:TEMPDAC_B/g'   IPMScalibration.bob

sed -i 's/RF3.MEZ1_AI_CH1_M/$(dev)$(ssa)-00:OPFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH1_C/$(dev)$(ssa)-00:OPFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH1_M/$(dev)$(ssa)-00:OPFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH1_C/$(dev)$(ssa)-00:OPFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH2_M/$(dev)$(ssa)-00:OPRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH2_C/$(dev)$(ssa)-00:OPRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH2_M/$(dev)$(ssa)-00:OPRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH2_C/$(dev)$(ssa)-00:OPRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH3_M/$(dev)$(ssa)-00:IPFwdADC_M/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH3_C/$(dev)$(ssa)-00:IPFwdADC_B/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH3_M/$(dev)$(ssa)-00:IPFwdDAC_M/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH3_C/$(dev)$(ssa)-00:IPFwdDAC_B/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH4_M/$(dev)$(ssa)-00:IPRefADC_M/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_CH4_C/$(dev)$(ssa)-00:IPRefADC_B/g'        IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH4_M/$(dev)$(ssa)-00:IPRefDAC_M/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ1_AI_DAC_CH4_C/$(dev)$(ssa)-00:IPRefDAC_B/g'    IPMScalibration.bob
sed -i 's/RF3.MEZ2_AI_CH1_M/$(dev)$(ssa)-00:IPRFPAADC_M/g'       IPMScalibration.bob
sed -i 's/RF3.MEZ2_AI_CH1_C/$(dev)$(ssa)-00:IPRFPAADC_B/g'       IPMScalibration.bob
sed -i 's/RF3.MEZ2_AI_DAC_CH1_M/$(dev)$(ssa)-00:IPRFPADAC_M/g'   IPMScalibration.bob
sed -i 's/RF3.MEZ2_AI_DAC_CH1_C/$(dev)$(ssa)-00:IPRFPADAC_B/g'   IPMScalibration.bob

sed -i 's/AI1.MEZ1_AI_CH7_M/$(dev)$(ssa)-00:VDRADC_M/g'          IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH7_C/$(dev)$(ssa)-00:VDRADC_B/g'          IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH7_M/$(dev)$(ssa)-00:VDRDAC_M/g'      IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH7_C/$(dev)$(ssa)-00:VDRDAC_B/g'      IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH8_M/$(dev)$(ssa)-00:IDRADC_M/g'          IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_CH8_C/$(dev)$(ssa)-00:IDRADC_B/g'          IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH8_M/$(dev)$(ssa)-00:IDRDAC_M/g'      IPMScalibration.bob
sed -i 's/AI1.MEZ1_AI_DAC_CH8_C/$(dev)$(ssa)-00:IDRDAC_B/g'      IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH7_M/$(dev)$(ssa)-00:FlowADC_M/g'         IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_CH7_C/$(dev)$(ssa)-00:FlowADC_B/g'         IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_CH7_M/$(dev)$(ssa)-00:FlowDAC_M/g'     IPMScalibration.bob
sed -i 's/AI2.MEZ1_AI_DAC_yH7_C/$(dev)$(ssa)-00:FlowDAC_B/g'     IPMScalibration.bob
